# ===================================
#  Form Behavior Config
# ===================================

name: ladylain.userpermissions::lang.permissions.menu_label
form: $/ladylain/userpermissions/models/permission/fields.yaml
modelClass: Ladylain\UserPermissions\Models\Permission

create:
    title: ladylain.userpermissions::lang.permissions.create_permission
    redirect: ladylain/userpermissions/permissions/update/:id
    redirectClose: ladylain/userpermissions/permissions

update:
    title: ladylain.userpermissions::lang.permissions.update_permission
    redirect: ladylain/userpermissions/permissions/update/:id
    redirectClose: ladylain/userpermissions/permissions

preview:
    title: ladylain.userpermissions::lang.permissions.view_permission

defaultRedirect: ladylain/userpermissions/permissions
