# ===================================
#  List Behavior Config
# ===================================

title: ladylain.userpermissions::lang.permissions.menu_label
list: ~/plugins/ladylain/userpermissions/models/permission/columns.yaml
modelClass: Ladylain\UserPermissions\Models\Permission
recordUrl: ladylain/userpermissions/permissions/update/:id

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
